import React from 'react';
import { 
  LayoutDashboard, 
  Map as MapIcon, 
  Database, 
  Settings, 
  Search, 
  Bell, 
  User, 
  Leaf, 
  ShieldCheck, 
  AlertTriangle,
  FileText,
  Menu,
  X,
  Upload,
  Cpu,
  Loader2,
  Layers,
  Activity,
  ArrowUpRight,
  Clock3,
  Filter,
  Download,
  Sparkles,
  Shield,
  Mail,
  KeyRound,
  Wallet,
  LogIn,
  UserPlus,
  LogOut,
  Gavel,
  Eye,
  EyeOff,
  Moon,
  Sun
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Map: MapIcon,
  Database: Database,
  Settings: Settings,
  Search: Search,
  Bell: Bell,
  User: User,
  Leaf: Leaf,
  Verified: ShieldCheck,
  Alert: AlertTriangle,
  Report: FileText,
  Menu: Menu,
  Close: X,
  Upload: Upload,
  AI: Cpu,
  Spinner: Loader2,
  Layers: Layers,
  Activity: Activity,
  TrendUp: ArrowUpRight,
  Clock: Clock3,
  Filter: Filter,
  Download: Download,
  Sparkles: Sparkles,
  Shield: Shield,
  Mail: Mail,
  Key: KeyRound,
  Wallet: Wallet,
  LogIn: LogIn,
  UserPlus: UserPlus,
  LogOut: LogOut,
  Gavel: Gavel,
  Eye: Eye,
  EyeOff: EyeOff,
  Moon: Moon,
  Sun: Sun
};
